// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package db

import (
	"context"
)

const countEnvironments = `-- name: CountEnvironments :one
SELECT count(*) FROM environments
`

func (q *Queries) CountEnvironments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnvironments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (name, kind, url)
VALUES (?, ?, ?)
RETURNING id, name, kind, url, created_at, updated_at
`

type CreateEnvironmentParams struct {
	Name string
	Kind string
	Url  string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment, arg.Name, arg.Kind, arg.Url)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, name, kind, url, created_at, updated_at FROM environments WHERE id = ? LIMIT 1
`

func (q *Queries) GetEnvironment(ctx context.Context, id int64) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, name, kind, url, created_at, updated_at FROM environments ORDER BY id
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
