// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git_credentials.sql

package db

import (
	"context"
)

const createGitCredential = `-- name: CreateGitCredential :one
INSERT INTO git_credentials (name, username, token_enc, created_by)
VALUES (?, ?, ?, ?)
RETURNING id, name, username, token_enc, created_by, created_at, updated_at
`

type CreateGitCredentialParams struct {
	Name      string
	Username  string
	TokenEnc  []byte
	CreatedBy string
}

func (q *Queries) CreateGitCredential(ctx context.Context, arg CreateGitCredentialParams) (GitCredential, error) {
	row := q.db.QueryRowContext(ctx, createGitCredential,
		arg.Name,
		arg.Username,
		arg.TokenEnc,
		arg.CreatedBy,
	)
	var i GitCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.TokenEnc,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitCredential = `-- name: DeleteGitCredential :exec
DELETE FROM git_credentials WHERE id = ?
`

func (q *Queries) DeleteGitCredential(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGitCredential, id)
	return err
}

const getGitCredential = `-- name: GetGitCredential :one
SELECT id, name, username, token_enc, created_by, created_at, updated_at FROM git_credentials WHERE id = ? LIMIT 1
`

func (q *Queries) GetGitCredential(ctx context.Context, id int64) (GitCredential, error) {
	row := q.db.QueryRowContext(ctx, getGitCredential, id)
	var i GitCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.TokenEnc,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitCredentials = `-- name: ListGitCredentials :many
SELECT id, name, username, token_enc, created_by, created_at, updated_at FROM git_credentials ORDER BY name
`

func (q *Queries) ListGitCredentials(ctx context.Context) ([]GitCredential, error) {
	rows, err := q.db.QueryContext(ctx, listGitCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitCredential{}
	for rows.Next() {
		var i GitCredential
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.TokenEnc,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitCredential = `-- name: UpdateGitCredential :one
UPDATE git_credentials
SET name = ?, username = ?, token_enc = ?, updated_at = unixepoch()
WHERE id = ?
RETURNING id, name, username, token_enc, created_by, created_at, updated_at
`

type UpdateGitCredentialParams struct {
	Name     string
	Username string
	TokenEnc []byte
	ID       int64
}

func (q *Queries) UpdateGitCredential(ctx context.Context, arg UpdateGitCredentialParams) (GitCredential, error) {
	row := q.db.QueryRowContext(ctx, updateGitCredential,
		arg.Name,
		arg.Username,
		arg.TokenEnc,
		arg.ID,
	)
	var i GitCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.TokenEnc,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
