// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Credential struct {
	ID                int64
	UserID            int64
	Type              string
	Secret            sql.NullString
	Provider          sql.NullString
	ProviderAccountID sql.NullString
	CreatedAt         int64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Token struct {
	ID        int64
	UserID    int64
	Purpose   string
	TokenHash string
	ExpiresAt int64
	UsedAt    sql.NullInt64
}

type User struct {
	ID              int64
	Email           string
	EmailVerifiedAt sql.NullInt64
	DisplayName     string
	Role            string
	CreatedAt       int64
	UpdatedAt       int64
}
