// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registries.sql

package db

import (
	"context"
)

const createRegistry = `-- name: CreateRegistry :one
INSERT INTO registries (name, server, username, password_enc, created_by)
VALUES (?, ?, ?, ?, ?)
RETURNING id, server, username, password_enc, created_by, created_at, updated_at, name
`

type CreateRegistryParams struct {
	Name        string
	Server      string
	Username    string
	PasswordEnc []byte
	CreatedBy   string
}

func (q *Queries) CreateRegistry(ctx context.Context, arg CreateRegistryParams) (Registry, error) {
	row := q.db.QueryRowContext(ctx, createRegistry,
		arg.Name,
		arg.Server,
		arg.Username,
		arg.PasswordEnc,
		arg.CreatedBy,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Server,
		&i.Username,
		&i.PasswordEnc,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deleteRegistry = `-- name: DeleteRegistry :exec
DELETE FROM registries WHERE id = ?
`

func (q *Queries) DeleteRegistry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRegistry, id)
	return err
}

const getRegistry = `-- name: GetRegistry :one
SELECT id, server, username, password_enc, created_by, created_at, updated_at, name FROM registries WHERE id = ? LIMIT 1
`

func (q *Queries) GetRegistry(ctx context.Context, id int64) (Registry, error) {
	row := q.db.QueryRowContext(ctx, getRegistry, id)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Server,
		&i.Username,
		&i.PasswordEnc,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getRegistryByServer = `-- name: GetRegistryByServer :one
SELECT id, server, username, password_enc, created_by, created_at, updated_at, name FROM registries WHERE server = ? LIMIT 1
`

func (q *Queries) GetRegistryByServer(ctx context.Context, server string) (Registry, error) {
	row := q.db.QueryRowContext(ctx, getRegistryByServer, server)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Server,
		&i.Username,
		&i.PasswordEnc,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const listRegistries = `-- name: ListRegistries :many
SELECT id, server, username, password_enc, created_by, created_at, updated_at, name FROM registries ORDER BY server
`

func (q *Queries) ListRegistries(ctx context.Context) ([]Registry, error) {
	rows, err := q.db.QueryContext(ctx, listRegistries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registry{}
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Server,
			&i.Username,
			&i.PasswordEnc,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegistry = `-- name: UpdateRegistry :one
UPDATE registries
SET name = ?, server = ?, username = ?, password_enc = ?, updated_at = unixepoch()
WHERE id = ?
RETURNING id, server, username, password_enc, created_by, created_at, updated_at, name
`

type UpdateRegistryParams struct {
	Name        string
	Server      string
	Username    string
	PasswordEnc []byte
	ID          int64
}

func (q *Queries) UpdateRegistry(ctx context.Context, arg UpdateRegistryParams) (Registry, error) {
	row := q.db.QueryRowContext(ctx, updateRegistry,
		arg.Name,
		arg.Server,
		arg.Username,
		arg.PasswordEnc,
		arg.ID,
	)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Server,
		&i.Username,
		&i.PasswordEnc,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
