// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasswordCredential = `-- name: CreatePasswordCredential :one
INSERT INTO credentials (user_id, type, secret)
VALUES (?, 'password', ?)
RETURNING id, user_id, type, secret, provider, provider_account_id, created_at
`

type CreatePasswordCredentialParams struct {
	UserID int64
	Secret sql.NullString
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createPasswordCredential, arg.UserID, arg.Secret)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Secret,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, role)
VALUES (?, ?, ?)
RETURNING id, email, email_verified_at, display_name, role, created_at, updated_at
`

type CreateUserParams struct {
	Email       string
	DisplayName string
	Role        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.DisplayName, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordCredential = `-- name: GetPasswordCredential :one
SELECT id, user_id, type, secret, provider, provider_account_id, created_at FROM credentials
WHERE user_id = ? AND type = 'password'
LIMIT 1
`

func (q *Queries) GetPasswordCredential(ctx context.Context, userID int64) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getPasswordCredential, userID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Secret,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, display_name, role, created_at, updated_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, display_name, role, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordCredential = `-- name: UpdatePasswordCredential :exec
UPDATE credentials
SET secret = ?
WHERE user_id = ? AND type = 'password'
`

type UpdatePasswordCredentialParams struct {
	Secret sql.NullString
	UserID int64
}

func (q *Queries) UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordCredential, arg.Secret, arg.UserID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = ?, updated_at = unixepoch()
WHERE id = ?
RETURNING id, email, email_verified_at, display_name, role, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName string
	ID          int64
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile, arg.DisplayName, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
