/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppEnvironmentsIdRouteImport } from './routes/_app/environments/$id'
import { Route as AppEnvironmentsIdIndexRouteImport } from './routes/_app/environments/$id/index'
import { Route as AppEnvironmentsIdVolumesRouteImport } from './routes/_app/environments/$id/volumes'
import { Route as AppEnvironmentsIdNetworksRouteImport } from './routes/_app/environments/$id/networks'
import { Route as AppEnvironmentsIdImagesRouteImport } from './routes/_app/environments/$id/images'
import { Route as AppEnvironmentsIdContainersRouteImport } from './routes/_app/environments/$id/containers'
import { Route as AppEnvironmentsIdStacksIndexRouteImport } from './routes/_app/environments/$id/stacks.index'
import { Route as AppEnvironmentsIdStacksNewRouteImport } from './routes/_app/environments/$id/stacks.new'
import { Route as AppEnvironmentsIdStacksNameEditRouteImport } from './routes/_app/environments/$id/stacks.$name.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentsIdRoute = AppEnvironmentsIdRouteImport.update({
  id: '/environments/$id',
  path: '/environments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentsIdIndexRoute = AppEnvironmentsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEnvironmentsIdRoute,
} as any)
const AppEnvironmentsIdVolumesRoute =
  AppEnvironmentsIdVolumesRouteImport.update({
    id: '/volumes',
    path: '/volumes',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdNetworksRoute =
  AppEnvironmentsIdNetworksRouteImport.update({
    id: '/networks',
    path: '/networks',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdImagesRoute = AppEnvironmentsIdImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AppEnvironmentsIdRoute,
} as any)
const AppEnvironmentsIdContainersRoute =
  AppEnvironmentsIdContainersRouteImport.update({
    id: '/containers',
    path: '/containers',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdStacksIndexRoute =
  AppEnvironmentsIdStacksIndexRouteImport.update({
    id: '/stacks/',
    path: '/stacks/',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdStacksNewRoute =
  AppEnvironmentsIdStacksNewRouteImport.update({
    id: '/stacks/new',
    path: '/stacks/new',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdStacksNameEditRoute =
  AppEnvironmentsIdStacksNameEditRouteImport.update({
    id: '/stacks/$name/edit',
    path: '/stacks/$name/edit',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/environments/$id': typeof AppEnvironmentsIdRouteWithChildren
  '/environments/$id/containers': typeof AppEnvironmentsIdContainersRoute
  '/environments/$id/images': typeof AppEnvironmentsIdImagesRoute
  '/environments/$id/networks': typeof AppEnvironmentsIdNetworksRoute
  '/environments/$id/volumes': typeof AppEnvironmentsIdVolumesRoute
  '/environments/$id/': typeof AppEnvironmentsIdIndexRoute
  '/environments/$id/stacks/new': typeof AppEnvironmentsIdStacksNewRoute
  '/environments/$id/stacks/': typeof AppEnvironmentsIdStacksIndexRoute
  '/environments/$id/stacks/$name/edit': typeof AppEnvironmentsIdStacksNameEditRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/': typeof AppIndexRoute
  '/environments/$id/containers': typeof AppEnvironmentsIdContainersRoute
  '/environments/$id/images': typeof AppEnvironmentsIdImagesRoute
  '/environments/$id/networks': typeof AppEnvironmentsIdNetworksRoute
  '/environments/$id/volumes': typeof AppEnvironmentsIdVolumesRoute
  '/environments/$id': typeof AppEnvironmentsIdIndexRoute
  '/environments/$id/stacks/new': typeof AppEnvironmentsIdStacksNewRoute
  '/environments/$id/stacks': typeof AppEnvironmentsIdStacksIndexRoute
  '/environments/$id/stacks/$name/edit': typeof AppEnvironmentsIdStacksNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/environments/$id': typeof AppEnvironmentsIdRouteWithChildren
  '/_app/environments/$id/containers': typeof AppEnvironmentsIdContainersRoute
  '/_app/environments/$id/images': typeof AppEnvironmentsIdImagesRoute
  '/_app/environments/$id/networks': typeof AppEnvironmentsIdNetworksRoute
  '/_app/environments/$id/volumes': typeof AppEnvironmentsIdVolumesRoute
  '/_app/environments/$id/': typeof AppEnvironmentsIdIndexRoute
  '/_app/environments/$id/stacks/new': typeof AppEnvironmentsIdStacksNewRoute
  '/_app/environments/$id/stacks/': typeof AppEnvironmentsIdStacksIndexRoute
  '/_app/environments/$id/stacks/$name/edit': typeof AppEnvironmentsIdStacksNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/setup'
    | '/environments/$id'
    | '/environments/$id/containers'
    | '/environments/$id/images'
    | '/environments/$id/networks'
    | '/environments/$id/volumes'
    | '/environments/$id/'
    | '/environments/$id/stacks/new'
    | '/environments/$id/stacks/'
    | '/environments/$id/stacks/$name/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/setup'
    | '/'
    | '/environments/$id/containers'
    | '/environments/$id/images'
    | '/environments/$id/networks'
    | '/environments/$id/volumes'
    | '/environments/$id'
    | '/environments/$id/stacks/new'
    | '/environments/$id/stacks'
    | '/environments/$id/stacks/$name/edit'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/setup'
    | '/_app/'
    | '/_app/environments/$id'
    | '/_app/environments/$id/containers'
    | '/_app/environments/$id/images'
    | '/_app/environments/$id/networks'
    | '/_app/environments/$id/volumes'
    | '/_app/environments/$id/'
    | '/_app/environments/$id/stacks/new'
    | '/_app/environments/$id/stacks/'
    | '/_app/environments/$id/stacks/$name/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/environments/$id': {
      id: '/_app/environments/$id'
      path: '/environments/$id'
      fullPath: '/environments/$id'
      preLoaderRoute: typeof AppEnvironmentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/environments/$id/': {
      id: '/_app/environments/$id/'
      path: '/'
      fullPath: '/environments/$id/'
      preLoaderRoute: typeof AppEnvironmentsIdIndexRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/volumes': {
      id: '/_app/environments/$id/volumes'
      path: '/volumes'
      fullPath: '/environments/$id/volumes'
      preLoaderRoute: typeof AppEnvironmentsIdVolumesRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/networks': {
      id: '/_app/environments/$id/networks'
      path: '/networks'
      fullPath: '/environments/$id/networks'
      preLoaderRoute: typeof AppEnvironmentsIdNetworksRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/images': {
      id: '/_app/environments/$id/images'
      path: '/images'
      fullPath: '/environments/$id/images'
      preLoaderRoute: typeof AppEnvironmentsIdImagesRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/containers': {
      id: '/_app/environments/$id/containers'
      path: '/containers'
      fullPath: '/environments/$id/containers'
      preLoaderRoute: typeof AppEnvironmentsIdContainersRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/stacks/': {
      id: '/_app/environments/$id/stacks/'
      path: '/stacks'
      fullPath: '/environments/$id/stacks/'
      preLoaderRoute: typeof AppEnvironmentsIdStacksIndexRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/stacks/new': {
      id: '/_app/environments/$id/stacks/new'
      path: '/stacks/new'
      fullPath: '/environments/$id/stacks/new'
      preLoaderRoute: typeof AppEnvironmentsIdStacksNewRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/stacks/$name/edit': {
      id: '/_app/environments/$id/stacks/$name/edit'
      path: '/stacks/$name/edit'
      fullPath: '/environments/$id/stacks/$name/edit'
      preLoaderRoute: typeof AppEnvironmentsIdStacksNameEditRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
  }
}

interface AppEnvironmentsIdRouteChildren {
  AppEnvironmentsIdContainersRoute: typeof AppEnvironmentsIdContainersRoute
  AppEnvironmentsIdImagesRoute: typeof AppEnvironmentsIdImagesRoute
  AppEnvironmentsIdNetworksRoute: typeof AppEnvironmentsIdNetworksRoute
  AppEnvironmentsIdVolumesRoute: typeof AppEnvironmentsIdVolumesRoute
  AppEnvironmentsIdIndexRoute: typeof AppEnvironmentsIdIndexRoute
  AppEnvironmentsIdStacksNewRoute: typeof AppEnvironmentsIdStacksNewRoute
  AppEnvironmentsIdStacksIndexRoute: typeof AppEnvironmentsIdStacksIndexRoute
  AppEnvironmentsIdStacksNameEditRoute: typeof AppEnvironmentsIdStacksNameEditRoute
}

const AppEnvironmentsIdRouteChildren: AppEnvironmentsIdRouteChildren = {
  AppEnvironmentsIdContainersRoute: AppEnvironmentsIdContainersRoute,
  AppEnvironmentsIdImagesRoute: AppEnvironmentsIdImagesRoute,
  AppEnvironmentsIdNetworksRoute: AppEnvironmentsIdNetworksRoute,
  AppEnvironmentsIdVolumesRoute: AppEnvironmentsIdVolumesRoute,
  AppEnvironmentsIdIndexRoute: AppEnvironmentsIdIndexRoute,
  AppEnvironmentsIdStacksNewRoute: AppEnvironmentsIdStacksNewRoute,
  AppEnvironmentsIdStacksIndexRoute: AppEnvironmentsIdStacksIndexRoute,
  AppEnvironmentsIdStacksNameEditRoute: AppEnvironmentsIdStacksNameEditRoute,
}

const AppEnvironmentsIdRouteWithChildren =
  AppEnvironmentsIdRoute._addFileChildren(AppEnvironmentsIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppEnvironmentsIdRoute: typeof AppEnvironmentsIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppEnvironmentsIdRoute: AppEnvironmentsIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
