/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppEnvironmentsIdRouteImport } from './routes/_app/environments/$id'
import { Route as AppEnvironmentsIdIndexRouteImport } from './routes/_app/environments/$id/index'
import { Route as AppEnvironmentsIdImagesRouteImport } from './routes/_app/environments/$id/images'
import { Route as AppEnvironmentsIdVolumesIndexRouteImport } from './routes/_app/environments/$id/volumes.index'
import { Route as AppEnvironmentsIdStacksIndexRouteImport } from './routes/_app/environments/$id/stacks.index'
import { Route as AppEnvironmentsIdNetworksIndexRouteImport } from './routes/_app/environments/$id/networks.index'
import { Route as AppEnvironmentsIdContainersIndexRouteImport } from './routes/_app/environments/$id/containers.index'
import { Route as AppEnvironmentsIdVolumesNameRouteImport } from './routes/_app/environments/$id/volumes.$name'
import { Route as AppEnvironmentsIdStacksNewRouteImport } from './routes/_app/environments/$id/stacks.new'
import { Route as AppEnvironmentsIdNetworksNetworkIdRouteImport } from './routes/_app/environments/$id/networks.$networkId'
import { Route as AppEnvironmentsIdContainersNewRouteImport } from './routes/_app/environments/$id/containers.new'
import { Route as AppEnvironmentsIdContainersContainerIdRouteImport } from './routes/_app/environments/$id/containers.$containerId'
import { Route as AppEnvironmentsIdStacksNameIndexRouteImport } from './routes/_app/environments/$id/stacks.$name.index'
import { Route as AppEnvironmentsIdStacksNameEditRouteImport } from './routes/_app/environments/$id/stacks.$name.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentsIdRoute = AppEnvironmentsIdRouteImport.update({
  id: '/environments/$id',
  path: '/environments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentsIdIndexRoute = AppEnvironmentsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEnvironmentsIdRoute,
} as any)
const AppEnvironmentsIdImagesRoute = AppEnvironmentsIdImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AppEnvironmentsIdRoute,
} as any)
const AppEnvironmentsIdVolumesIndexRoute =
  AppEnvironmentsIdVolumesIndexRouteImport.update({
    id: '/volumes/',
    path: '/volumes/',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdStacksIndexRoute =
  AppEnvironmentsIdStacksIndexRouteImport.update({
    id: '/stacks/',
    path: '/stacks/',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdNetworksIndexRoute =
  AppEnvironmentsIdNetworksIndexRouteImport.update({
    id: '/networks/',
    path: '/networks/',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdContainersIndexRoute =
  AppEnvironmentsIdContainersIndexRouteImport.update({
    id: '/containers/',
    path: '/containers/',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdVolumesNameRoute =
  AppEnvironmentsIdVolumesNameRouteImport.update({
    id: '/volumes/$name',
    path: '/volumes/$name',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdStacksNewRoute =
  AppEnvironmentsIdStacksNewRouteImport.update({
    id: '/stacks/new',
    path: '/stacks/new',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdNetworksNetworkIdRoute =
  AppEnvironmentsIdNetworksNetworkIdRouteImport.update({
    id: '/networks/$networkId',
    path: '/networks/$networkId',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdContainersNewRoute =
  AppEnvironmentsIdContainersNewRouteImport.update({
    id: '/containers/new',
    path: '/containers/new',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdContainersContainerIdRoute =
  AppEnvironmentsIdContainersContainerIdRouteImport.update({
    id: '/containers/$containerId',
    path: '/containers/$containerId',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdStacksNameIndexRoute =
  AppEnvironmentsIdStacksNameIndexRouteImport.update({
    id: '/stacks/$name/',
    path: '/stacks/$name/',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)
const AppEnvironmentsIdStacksNameEditRoute =
  AppEnvironmentsIdStacksNameEditRouteImport.update({
    id: '/stacks/$name/edit',
    path: '/stacks/$name/edit',
    getParentRoute: () => AppEnvironmentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/environments/$id': typeof AppEnvironmentsIdRouteWithChildren
  '/environments/$id/images': typeof AppEnvironmentsIdImagesRoute
  '/environments/$id/': typeof AppEnvironmentsIdIndexRoute
  '/environments/$id/containers/$containerId': typeof AppEnvironmentsIdContainersContainerIdRoute
  '/environments/$id/containers/new': typeof AppEnvironmentsIdContainersNewRoute
  '/environments/$id/networks/$networkId': typeof AppEnvironmentsIdNetworksNetworkIdRoute
  '/environments/$id/stacks/new': typeof AppEnvironmentsIdStacksNewRoute
  '/environments/$id/volumes/$name': typeof AppEnvironmentsIdVolumesNameRoute
  '/environments/$id/containers/': typeof AppEnvironmentsIdContainersIndexRoute
  '/environments/$id/networks/': typeof AppEnvironmentsIdNetworksIndexRoute
  '/environments/$id/stacks/': typeof AppEnvironmentsIdStacksIndexRoute
  '/environments/$id/volumes/': typeof AppEnvironmentsIdVolumesIndexRoute
  '/environments/$id/stacks/$name/edit': typeof AppEnvironmentsIdStacksNameEditRoute
  '/environments/$id/stacks/$name/': typeof AppEnvironmentsIdStacksNameIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/': typeof AppIndexRoute
  '/environments/$id/images': typeof AppEnvironmentsIdImagesRoute
  '/environments/$id': typeof AppEnvironmentsIdIndexRoute
  '/environments/$id/containers/$containerId': typeof AppEnvironmentsIdContainersContainerIdRoute
  '/environments/$id/containers/new': typeof AppEnvironmentsIdContainersNewRoute
  '/environments/$id/networks/$networkId': typeof AppEnvironmentsIdNetworksNetworkIdRoute
  '/environments/$id/stacks/new': typeof AppEnvironmentsIdStacksNewRoute
  '/environments/$id/volumes/$name': typeof AppEnvironmentsIdVolumesNameRoute
  '/environments/$id/containers': typeof AppEnvironmentsIdContainersIndexRoute
  '/environments/$id/networks': typeof AppEnvironmentsIdNetworksIndexRoute
  '/environments/$id/stacks': typeof AppEnvironmentsIdStacksIndexRoute
  '/environments/$id/volumes': typeof AppEnvironmentsIdVolumesIndexRoute
  '/environments/$id/stacks/$name/edit': typeof AppEnvironmentsIdStacksNameEditRoute
  '/environments/$id/stacks/$name': typeof AppEnvironmentsIdStacksNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/environments/$id': typeof AppEnvironmentsIdRouteWithChildren
  '/_app/environments/$id/images': typeof AppEnvironmentsIdImagesRoute
  '/_app/environments/$id/': typeof AppEnvironmentsIdIndexRoute
  '/_app/environments/$id/containers/$containerId': typeof AppEnvironmentsIdContainersContainerIdRoute
  '/_app/environments/$id/containers/new': typeof AppEnvironmentsIdContainersNewRoute
  '/_app/environments/$id/networks/$networkId': typeof AppEnvironmentsIdNetworksNetworkIdRoute
  '/_app/environments/$id/stacks/new': typeof AppEnvironmentsIdStacksNewRoute
  '/_app/environments/$id/volumes/$name': typeof AppEnvironmentsIdVolumesNameRoute
  '/_app/environments/$id/containers/': typeof AppEnvironmentsIdContainersIndexRoute
  '/_app/environments/$id/networks/': typeof AppEnvironmentsIdNetworksIndexRoute
  '/_app/environments/$id/stacks/': typeof AppEnvironmentsIdStacksIndexRoute
  '/_app/environments/$id/volumes/': typeof AppEnvironmentsIdVolumesIndexRoute
  '/_app/environments/$id/stacks/$name/edit': typeof AppEnvironmentsIdStacksNameEditRoute
  '/_app/environments/$id/stacks/$name/': typeof AppEnvironmentsIdStacksNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/setup'
    | '/environments/$id'
    | '/environments/$id/images'
    | '/environments/$id/'
    | '/environments/$id/containers/$containerId'
    | '/environments/$id/containers/new'
    | '/environments/$id/networks/$networkId'
    | '/environments/$id/stacks/new'
    | '/environments/$id/volumes/$name'
    | '/environments/$id/containers/'
    | '/environments/$id/networks/'
    | '/environments/$id/stacks/'
    | '/environments/$id/volumes/'
    | '/environments/$id/stacks/$name/edit'
    | '/environments/$id/stacks/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/setup'
    | '/'
    | '/environments/$id/images'
    | '/environments/$id'
    | '/environments/$id/containers/$containerId'
    | '/environments/$id/containers/new'
    | '/environments/$id/networks/$networkId'
    | '/environments/$id/stacks/new'
    | '/environments/$id/volumes/$name'
    | '/environments/$id/containers'
    | '/environments/$id/networks'
    | '/environments/$id/stacks'
    | '/environments/$id/volumes'
    | '/environments/$id/stacks/$name/edit'
    | '/environments/$id/stacks/$name'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/setup'
    | '/_app/'
    | '/_app/environments/$id'
    | '/_app/environments/$id/images'
    | '/_app/environments/$id/'
    | '/_app/environments/$id/containers/$containerId'
    | '/_app/environments/$id/containers/new'
    | '/_app/environments/$id/networks/$networkId'
    | '/_app/environments/$id/stacks/new'
    | '/_app/environments/$id/volumes/$name'
    | '/_app/environments/$id/containers/'
    | '/_app/environments/$id/networks/'
    | '/_app/environments/$id/stacks/'
    | '/_app/environments/$id/volumes/'
    | '/_app/environments/$id/stacks/$name/edit'
    | '/_app/environments/$id/stacks/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/environments/$id': {
      id: '/_app/environments/$id'
      path: '/environments/$id'
      fullPath: '/environments/$id'
      preLoaderRoute: typeof AppEnvironmentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/environments/$id/': {
      id: '/_app/environments/$id/'
      path: '/'
      fullPath: '/environments/$id/'
      preLoaderRoute: typeof AppEnvironmentsIdIndexRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/images': {
      id: '/_app/environments/$id/images'
      path: '/images'
      fullPath: '/environments/$id/images'
      preLoaderRoute: typeof AppEnvironmentsIdImagesRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/volumes/': {
      id: '/_app/environments/$id/volumes/'
      path: '/volumes'
      fullPath: '/environments/$id/volumes/'
      preLoaderRoute: typeof AppEnvironmentsIdVolumesIndexRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/stacks/': {
      id: '/_app/environments/$id/stacks/'
      path: '/stacks'
      fullPath: '/environments/$id/stacks/'
      preLoaderRoute: typeof AppEnvironmentsIdStacksIndexRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/networks/': {
      id: '/_app/environments/$id/networks/'
      path: '/networks'
      fullPath: '/environments/$id/networks/'
      preLoaderRoute: typeof AppEnvironmentsIdNetworksIndexRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/containers/': {
      id: '/_app/environments/$id/containers/'
      path: '/containers'
      fullPath: '/environments/$id/containers/'
      preLoaderRoute: typeof AppEnvironmentsIdContainersIndexRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/volumes/$name': {
      id: '/_app/environments/$id/volumes/$name'
      path: '/volumes/$name'
      fullPath: '/environments/$id/volumes/$name'
      preLoaderRoute: typeof AppEnvironmentsIdVolumesNameRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/stacks/new': {
      id: '/_app/environments/$id/stacks/new'
      path: '/stacks/new'
      fullPath: '/environments/$id/stacks/new'
      preLoaderRoute: typeof AppEnvironmentsIdStacksNewRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/networks/$networkId': {
      id: '/_app/environments/$id/networks/$networkId'
      path: '/networks/$networkId'
      fullPath: '/environments/$id/networks/$networkId'
      preLoaderRoute: typeof AppEnvironmentsIdNetworksNetworkIdRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/containers/new': {
      id: '/_app/environments/$id/containers/new'
      path: '/containers/new'
      fullPath: '/environments/$id/containers/new'
      preLoaderRoute: typeof AppEnvironmentsIdContainersNewRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/containers/$containerId': {
      id: '/_app/environments/$id/containers/$containerId'
      path: '/containers/$containerId'
      fullPath: '/environments/$id/containers/$containerId'
      preLoaderRoute: typeof AppEnvironmentsIdContainersContainerIdRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/stacks/$name/': {
      id: '/_app/environments/$id/stacks/$name/'
      path: '/stacks/$name'
      fullPath: '/environments/$id/stacks/$name/'
      preLoaderRoute: typeof AppEnvironmentsIdStacksNameIndexRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
    '/_app/environments/$id/stacks/$name/edit': {
      id: '/_app/environments/$id/stacks/$name/edit'
      path: '/stacks/$name/edit'
      fullPath: '/environments/$id/stacks/$name/edit'
      preLoaderRoute: typeof AppEnvironmentsIdStacksNameEditRouteImport
      parentRoute: typeof AppEnvironmentsIdRoute
    }
  }
}

interface AppEnvironmentsIdRouteChildren {
  AppEnvironmentsIdImagesRoute: typeof AppEnvironmentsIdImagesRoute
  AppEnvironmentsIdIndexRoute: typeof AppEnvironmentsIdIndexRoute
  AppEnvironmentsIdContainersContainerIdRoute: typeof AppEnvironmentsIdContainersContainerIdRoute
  AppEnvironmentsIdContainersNewRoute: typeof AppEnvironmentsIdContainersNewRoute
  AppEnvironmentsIdNetworksNetworkIdRoute: typeof AppEnvironmentsIdNetworksNetworkIdRoute
  AppEnvironmentsIdStacksNewRoute: typeof AppEnvironmentsIdStacksNewRoute
  AppEnvironmentsIdVolumesNameRoute: typeof AppEnvironmentsIdVolumesNameRoute
  AppEnvironmentsIdContainersIndexRoute: typeof AppEnvironmentsIdContainersIndexRoute
  AppEnvironmentsIdNetworksIndexRoute: typeof AppEnvironmentsIdNetworksIndexRoute
  AppEnvironmentsIdStacksIndexRoute: typeof AppEnvironmentsIdStacksIndexRoute
  AppEnvironmentsIdVolumesIndexRoute: typeof AppEnvironmentsIdVolumesIndexRoute
  AppEnvironmentsIdStacksNameEditRoute: typeof AppEnvironmentsIdStacksNameEditRoute
  AppEnvironmentsIdStacksNameIndexRoute: typeof AppEnvironmentsIdStacksNameIndexRoute
}

const AppEnvironmentsIdRouteChildren: AppEnvironmentsIdRouteChildren = {
  AppEnvironmentsIdImagesRoute: AppEnvironmentsIdImagesRoute,
  AppEnvironmentsIdIndexRoute: AppEnvironmentsIdIndexRoute,
  AppEnvironmentsIdContainersContainerIdRoute:
    AppEnvironmentsIdContainersContainerIdRoute,
  AppEnvironmentsIdContainersNewRoute: AppEnvironmentsIdContainersNewRoute,
  AppEnvironmentsIdNetworksNetworkIdRoute:
    AppEnvironmentsIdNetworksNetworkIdRoute,
  AppEnvironmentsIdStacksNewRoute: AppEnvironmentsIdStacksNewRoute,
  AppEnvironmentsIdVolumesNameRoute: AppEnvironmentsIdVolumesNameRoute,
  AppEnvironmentsIdContainersIndexRoute: AppEnvironmentsIdContainersIndexRoute,
  AppEnvironmentsIdNetworksIndexRoute: AppEnvironmentsIdNetworksIndexRoute,
  AppEnvironmentsIdStacksIndexRoute: AppEnvironmentsIdStacksIndexRoute,
  AppEnvironmentsIdVolumesIndexRoute: AppEnvironmentsIdVolumesIndexRoute,
  AppEnvironmentsIdStacksNameEditRoute: AppEnvironmentsIdStacksNameEditRoute,
  AppEnvironmentsIdStacksNameIndexRoute: AppEnvironmentsIdStacksNameIndexRoute,
}

const AppEnvironmentsIdRouteWithChildren =
  AppEnvironmentsIdRoute._addFileChildren(AppEnvironmentsIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppEnvironmentsIdRoute: typeof AppEnvironmentsIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppEnvironmentsIdRoute: AppEnvironmentsIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
